name: Lint

on: [pull_request]

permissions:
  contents: read

jobs:
  pr-title:
    runs-on: ubuntu-latest
    name: Check PR title format
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5.5.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  editorconfig:
    runs-on: ubuntu-latest
    name: Check editorconfig
    steps:
      - uses: actions/checkout@v4
      - run: pip install --break-system-packages editorconfig-checker=="2.7.3"
      - run: ec

  typos:
    runs-on: ubuntu-latest
    name: Check spelling
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.21.0

  license-headers:
    runs-on: ubuntu-latest
    name: Check license headers
    steps:
      - uses: actions/checkout@v4
      - run: cargo install licensesnip@1.5.0
      - run: licensesnip check

  prettier:
    runs-on: ubuntu-latest
    name: Check frontent code formatting
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: '--check **/*.{js,ts,tsx,css,html}'

  black:
    runs-on: ubuntu-latest
    name: Check Python formatting
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable

  check-all:
    name: Check if all lint jobs succeeded
    if: always()
    needs:
      - pr-title
      - editorconfig
      - typos
      - license-headers
      - prettier
      - black
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether all needed jobs succeeded
      uses: re-actors/alls-green@v1.2.2
      with:
        jobs: ${{ toJSON(needs) }}
